### ISSUE TITLE
Icon Sizing

### ISSUE THREAD

**Issue by antony** [dylanblokhuis/svelte-feather-icons#1]
Hi - thanks for this library, it is excellent!

I'd like to make one suggestion - right now the icons have a hardcoded size of 24px x 24px. If you were to rewrite the SVGs as you ran `build.js`, you could set that to 100% 100%, meaning that the icons would take the size of their container.

**Comment by dylanblokhuis** [comment]
Fixed in latest commit! thanks for raising the issue.

**Comment by antony** [comment]
Wooh! Awesome.

One word of advice though - this should be a minor release, it's a breaking change, since all my icons are now absolutely huge :)

Might be worth unpublishing that release and bumping minor!

**Comment by dylanblokhuis** [comment]
Appreciate the advice! Will look into it!

**Comment by dylanblokhuis** [comment]
Just bumped the version to 2.0.0 since this is a breaking change yeah.. learned about semver. thank you again!
