### ISSUE TITLE
svelte3 dont work size

### ISSUE THREAD

**Issue by impfromliga** [dylanblokhuis/svelte-feather-icons#2]
<script>
        import { AirplayIcon } from 'svelte-feather-icons'
    </script>
    
    
    <AirplayIcon />

    
    <airplay-icon />

    
    <airplay-icon size="25" class="custom-class"/>

**Comment by JefferyHus** [comment]
Size will not work for you, the source code isn't taking it in considerations. I doubt if I open a PR that it will be accepted

**Comment by cimm** [comment]
Same for me, I expected `size="1.5x"` to work as it does in [vue-feather-icons](https://github.com/egoist/vue-feather-icons). @dylanblokhuis is this something you are considering/would be open to accept a pull request for?

My current workaround adds a bit of unnecessary HTML. You can't size the SVG element directly in CSS as (I think) it's loaded after the CSS.

```html
<style>
  span { width: 1em; display: inline-block; }
</style>

<p>Lorem ipsum <span><AirplayIcon/></span> dolor sit amet.</p>
```

**Comment by dylanblokhuis** [comment]
I recognize it's annoying to keep adding parent elements to size the icon. I might PR this later today.
