### ISSUE TITLE
TypeScript compatibility ( Intellisense )

### ISSUE THREAD

**Issue by Hygor** [dylanblokhuis/svelte-feather-icons#7]
I just started to use TypeScript in my Svelte projects since it's fully compatible using the script tag with lang attribute: 

```js
<script lang='typescript'>
// do your code here...
</script>
```

But for the `svelte-feather-icons` it still missing the definitions of the types `@types/svelte-feather-icons` to use it with IDE IntelliSense.

**Comment by dylanblokhuis** [comment]
Type definitions are added, although it's not complete since (in my testing) it did not autocomplete props.

**Comment by dylanblokhuis** [comment]
#13 fixed this issue
